# https://medium.com/@dummydevops/containerizing-a-flask-react-app-with-docker-compose-5c06ef73cc8f
version: "3"
services:
  # db:
  #   image: postgres
  #   command: postgres -c listen_addresses='*'
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_DB: journal
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #   volumes:
  #     - ./api/data:/docker-entrypoint-initdb.d
  #   ports:
  #     - 5432:5432

  api:
    build: ./api
    expose:
      - 5000
    ports:
      - 5000:5000
    working_dir: /home/api
    volumes:
      - ./api:/home/api
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_PORT=5000
      - FLASK_ENV=development
    # depends_on:
    #   - db

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /home/frontend
    volumes:
      - ./frontend/src:/home/frontend/src
      - ./frontend/public:/home/frontend/public
    depends_on:
      - api
